apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato-container
          image: ramakrishna737/foodsite:v1
          ports:
            - containerPort: 8080
