apiVersion: apps/v1
kind: Deployment
metadata:
  name:  argocd
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: count1
          image: ramakrishna737/zomato/v1
          ports:
            - containerPort: 8080
