apiVersion: v1
kind: Service
metadata:
  name: argo-service  # Change if your app is in a different namespace
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - name: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30443 # Port your app listens on inside the pod
