---
apiVersion: v1
kinnd: Service
metadata:
  name: argocd-service
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30443
