apiVersion: v1
kind: Service
metadata:
  name: kittu
  namespace: default
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30550
