apiVersion: v1
kind: Service
metadata:
  name: argo-service # or whatever namespace you're using
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30443 
