apiVersion: v1
kind: Service
metadata:
  name: kittu
  namespace: default
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30443
