apiVersion: v1
kind: Service
metadata:
  name: argocd-service  # Change if your app is in a different namespace
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 8080         # Port exposed by LoadBalancer
      targetPort: 3000 # Port your app listens on inside the pod
