apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30550
